#!/bin/bash

# Personal Finance Tracker - Release Helper Script
# This script provides a quick reference for triggering releases

echo "========================================="
echo "Personal Finance Tracker - Release Tool"
echo "========================================="
echo ""
echo "To create a release, go to:"
echo "  GitHub → Actions → Release → Run workflow"
echo ""
echo "Or use the GitHub CLI:"
echo ""
echo "1. Patch Release (bug fixes only):"
echo "   gh workflow run release.yml -f package_version=1.0.1"
echo ""
echo "2. Minor Release (new features):"
echo "   gh workflow run release.yml -f package_version=1.1.0"
echo ""
echo "3. Major Release (breaking changes):"
echo "   gh workflow run release.yml -f package_version=2.0.0"
echo ""
echo "4. With dependency updates:"
echo "   gh workflow run release.yml \\"
echo "     -f package_version=1.1.0 \\"
echo "     -f update_dependencies=true \\"
echo "     -f pytest_version=7.0.0 \\"
echo "     -f black_version=22.0.0"
echo ""
echo "========================================="
echo ""
echo "📚 For more details, see: RELEASE_GUIDE.md"
echo ""
